"""empty message

Revision ID: 9d5d3efcb1e7
Revises: ba40f506a7ab
Create Date: 2019-06-14 18:52:11.082262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5d3efcb1e7'
down_revision = 'ba40f506a7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_list', sa.Column('address', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'contact_list', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_list', type_='unique')
    op.drop_column('contact_list', 'address')
    # ### end Alembic commands ###
